[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production"
NEXTAUTH_URL = "https://licensorflow.railway.app"
NEXTAUTH_SECRET = "your-nextauth-secret-here"

[environments.staging]
NODE_ENV = "staging"
NEXTAUTH_URL = "https://licensorflow-staging.railway.app"
NEXTAUTH_SECRET = "your-staging-nextauth-secret-here"
